#!/usr/bin/env bash
# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
# Similarly, if the wifi interface exists but no connection is active, show
# nothing
[[ ! -d /sys/class/net/wlp59s0/wireless || \
    "$(cat /sys/class/net/wlp59s0/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

SSID=$(iw wlp59s0 info | awk '/ssid/ {print $2}')

#------------------------------------------------------------------------

echo "$SSID" # full text
echo "$SSID" # short text
echo "#00FF00" # color
